name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # 'packages: write' is typically for GitHub Container Registry (ghcr.io)
      # While not strictly needed for Docker Hub, it doesn't hurt and
      # might be useful if you later decide to push to both or ghcr.io.
      packages: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use your Docker Hub username secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Use your Docker Hub PAT secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Assumes your Dockerfile is in the root of the repository
          push: true
          # Define multiple tags: 'latest' and a tag based on the commit SHA
          # Replace 'YOUR_DOCKERHUB_USERNAME' with your actual Docker Hub username
          # Replace 'filmwhisper-bitmagnet' if your Docker Hub repository name is different
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/filmwhisper-bitmagnet:latest
            ${{ secrets.DOCKER_USERNAME }}/filmwhisper-bitmagnet:${{ github.sha }}
          cache-from: type=gha # Cache layers from previous GitHub Actions runs
          cache-to: type=gha,mode=max # Store new layers to GitHub Actions cache for future runs
