name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 'packages: write' is still useful if you ever decide to push to GHCR in addition or instead

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use your Docker Hub username secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Use your Docker Hub PAT secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # IMPORTANT: Replace YOUR_DOCKERHUB_USERNAME and YOUR_REPO_NAME
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/filmwhisper-bitmagnet:latest # Using your actual repo name
            ${{ secrets.DOCKER_USERNAME }}/filmwhisper-bitmagnet:${{ github.sha }} # Add a tag with the commit SHA for versioning
          cache-from: type=gha
          cache-to: type=gha,mode=max
